MODSOURMAN-664 Remove Kafka cache from QuickMarc handlers
folio-org/mod-source-record-manager pull request #550
Opened 2022-01-10 12:40 UTC by Shans-Kaluhin

## Purpose
Kafka Cache is used in QuickMarcUpdateKafkaHandler in SRM. Just remove Kafka cache (consumer receiving QM_COMPLETED supports deduplication).

## Learning
[MODSOURMAN-664](https://issues.folio.org/browse/MODSOURMAN-664)

2022-01-10 15:59 UTC, psmagin requested changes

2022-01-10 15:59 UTC, psmagin commented on mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/QuickMarcUpdateKafkaHandler.java
> +  private final EventProcessedService eventProcessedService;
There is no need for using this service. We can just remove the Kafka cache and rely on the database and handler that we have in mod-quick-marc.

2022-01-11 07:37 UTC, SerhiiNosko approved these changes

2022-01-11 12:35 UTC, psmagin approved these changes

2022-01-11 13:30 UTC, merged